[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
send_message = "0x8de35903e9899f04fc82f0107a9174ee20bd0b18bb5e35d75830998c76042687"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

